// DeepL supported languages with Azure code mapping (where available)
export const DEEPL_LANGUAGES = [
  { deepl: 'BG', name: 'Bulgarian', azure: 'bg-BG' },
  { deepl: 'CS', name: 'Czech', azure: 'cs-CZ' },
  { deepl: 'DA', name: 'Danish', azure: 'da-DK' },
  { deepl: 'DE', name: 'German', azure: 'de-DE' },
  { deepl: 'EL', name: 'Greek', azure: 'el-GR' },
  // { deepl: "EN", name: "English", azure: "en-US" },
  { deepl: 'EN-GB', name: 'English (British)', azure: 'en-GB' },
  { deepl: 'EN-US', name: 'English (American)', azure: 'en-US' },
  { deepl: 'ES', name: 'Spanish', azure: 'es-ES' },
  { deepl: 'ET', name: 'Estonian', azure: 'et-EE' },
  { deepl: 'FI', name: 'Finnish', azure: 'fi-FI' },
  { deepl: 'FR', name: 'French', azure: 'fr-FR' },
  { deepl: 'HU', name: 'Hungarian', azure: 'hu-HU' },
  { deepl: 'ID', name: 'Indonesian', azure: 'id-ID' },
  { deepl: 'IT', name: 'Italian', azure: 'it-IT' },
  { deepl: 'JA', name: 'Japanese', azure: 'ja-JP' },
  { deepl: 'KO', name: 'Korean', azure: 'ko-KR' },
  { deepl: 'LT', name: 'Lithuanian', azure: 'lt-LT' },
  { deepl: 'LV', name: 'Latvian', azure: 'lv-LV' },
  { deepl: 'NB', name: 'Norwegian Bokmål', azure: 'nb-NO' },
  { deepl: 'NL', name: 'Dutch', azure: 'nl-NL' },
  { deepl: 'PL', name: 'Polish', azure: 'pl-PL' },
  { deepl: 'PT', name: 'Portuguese', azure: 'pt-PT' },
  { deepl: 'PT-BR', name: 'Portuguese (Brazilian)', azure: 'pt-BR' },
  { deepl: 'PT-PT', name: 'Portuguese (European)', azure: 'pt-PT' },
  { deepl: 'RO', name: 'Romanian', azure: 'ro-RO' },
  { deepl: 'RU', name: 'Russian', azure: 'ru-RU' },
  { deepl: 'SK', name: 'Slovak', azure: 'sk-SK' },
  { deepl: 'SL', name: 'Slovenian', azure: 'sl-SI' },
  { deepl: 'SV', name: 'Swedish', azure: 'sv-SE' },
  { deepl: 'TR', name: 'Turkish', azure: 'tr-TR' },
  { deepl: 'UK', name: 'Ukrainian', azure: 'uk-UA' },
  { deepl: 'ZH', name: 'Chinese', azure: 'zh-CN' }
  // Add more as DeepL/Azure support grows
];
